#!/bin/bash
#
# Automatically generated by ./build.sh on Sun Jan 15 15:32:41 ICT 2017
export BOOST_HOME="/home/sophatvathana/cameralib/1_63_0/gcc/5.4.0"
export LD_LIBRARY_PATH="${BOOST_HOME}/lib:${LD_LIBRARY_PATH}"
source "/usr/local/lib//setup.sh"
