#!/bin/bash
#
# Automatically generated by ./build.sh on Tue Jan 17 18:47:37 ICT 2017
export BOOST_HOME="/home/sophatvathana/Desktop/cameralib/1_63_0/gcc/5.3.1"
export LD_LIBRARY_PATH="${BOOST_HOME}/lib:${LD_LIBRARY_PATH}"
source "/usr/local/include//setup.sh"
